### ISSUE TITLE
Update About Content

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/MN-Low-Flow#16]
2 Sections (see below for details):

- [ ] About the Application

- [ ] Disclaimer

**Comment by HansVraga** [comment]
MPCA has no about content they want to see.
I'll get some boilerplate language and pass it on here.

**Comment by HansVraga** [comment]
**Disclaimer**:
Include the following language:

USGS Data Disclaimer
Unless otherwise stated, all data, metadata and related materials are considered to satisfy the quality standards relative to the purpose for which the data were collected. Although these data and associated metadata have been reviewed for accuracy and completeness and approved for release by the U.S. Geological Survey (USGS), no warranty expressed or implied is made regarding the display or utility of the data for other purposes, nor on all computer systems, nor shall the act of distribution constitute any such warranty.

USGS Software Disclaimer
This software has been approved for release by the U.S. Geological Survey (USGS). Although the software has been subjected to rigorous review, the USGS reserves the right to update the software as needed pursuant to further analysis and review. No warranty, expressed or implied, is made by the USGS or the U.S. Government as to the functionality of the software and related material nor shall the fact of release constitute any such warranty. Furthermore, the software is released on condition that neither the USGS nor the U.S. Government shall be held liable for any damages resulting from its authorized or unauthorized use.

USGS Product Names Disclaimer
Any use of trade, firm, or product names is for descriptive purposes only and does not imply endorsement by the U.S. Government.

**Comment by HansVraga** [comment]
**About the Application:**
Include the following language:

The USGS Minnesota Low-Flow web application is used as a preparation and management tool for tracking, visualization, and management of historic and future low flow measurements for the state of Minnesota. 

Reference: [Methods Used to Compute Low-Flow Frequency Characteristics for Continuous-Record Streamflow Stations in Minnesota, 2006](https://pubs.usgs.gov/of/2007/1033/)

**Comment by HansVraga** [comment]
Include in the "about"
![image](https://user-images.githubusercontent.com/12058013/68155901-4a24dc00-ff10-11e9-9bb0-e7ca1b565ea0.png)

**Comment by esmyers** [comment]
Wasn't 100% clear on the locations for some items, but these changes are in code now.
