### ISSUE TITLE
Add Water Treatment Plants outflow points

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/MN-Low-Flow#20]
Will need to get the point layer from MPCA

**Comment by HansVraga** [comment]
Update from MPCA:
>I checked with our GIS staff and the MPCA needs to make the wastewater discharges layer a data service and post on the MN Geospatial Commons website. The data will then be continually updated and available to feed the low flow map, without additional work on anyone’s part.  MPCA also needs to enable the data layer to be filtered so that USGS can display the stations identified by MPCA, to reduce clutter in the map. There is already an existing request to post the data, and our request has been added to the ticket to make this a higher priority to complete.  I’ll keep in touch about the status of this.

**Comment by HansVraga** [comment]
Update from MPCA:
>Hi Chris,
>Follow up to our phone conversation this morning regarding the Low Flow map.
> 
>Here’s what the updated USGS Low Flow web page should be accessing for our wastewater discharge layer.
>
>
> 
> Choose the following Layer:
> Active wastewater surface water discharges (excluding general non-metallic mining permit) (ID: 6)
> https://pca-gis02.pca.state.mn.us/arcgis/rest/services/agol/ww_facility/MapServer/6
>  
> This is a filtered version that excludes non-metallic mining discharges.  There are many stations, that clutter the map and are not always relevant for our unit’s work. These permits were also known as ‘construction sand and gravel, aggregate and hot mix asphalt activities’   
>  
> http://www.arcgis.com/home/webmap/viewer.html?webmap=cdc20462c50f4d2c8f2c71f504135116&extent=-97.5637,43.2315,-90.2468,46.3946
>  
>  
> *The other items we discussed are related to preliminary info about what a low flow gap analysis would entail. Also if you can share plan/project info from similar(?) peak flow gap analysis for MNDOT, etc.
>  
> MPCA will have an internal meeting in January regarding the scope of services for the next iteration of the USGS Master Contract (for work in 2021).
>  
> thanks,
> Carol

**Comment by lprivette** [comment]
test
