### ISSUE TITLE
Add HUC 8 layer with labels to map

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/MN-Low-Flow#22]

**Comment by lprivette** [comment]
https://fwsprimary.wim.usgs.gov/server/rest/services/HUCs/MapServer/1/query?where=STATES+%3D+%27MN%27&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=false&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&resultOffset=&resultRecordCount=&queryByDistance=&returnExtentsOnly=false&datumTransformation=&parameterValues=&rangeValues=&f=html

**Comment by esmyers** [comment]
Services are not configured to add labels so I added this popup instead. 
![image](https://user-images.githubusercontent.com/2495167/68521547-df550700-0267-11ea-89ad-0d5f1696a2d3.png)

**Comment by esmyers** [comment]
Also @NathanKrawza I think there is a bug in the esri-leaflet API.  It wouldn't allow a the bindPopup() event to work with the layerDefs set on the layer.  Your code worked fine if I removed the layerDefs.  A weird issue.  I just made a custom click event so you can take a look and see the workaround if you'd like.

**Comment by esmyers** [comment]
Done with a popup since on-map labels weren't feasible.

**Comment by HansVraga** [comment]
https://www.arcgis.com/home/webmap/viewer.html?useExisting=1&layers=4c08f2e2b13741da96ad4a8f6aa5e36a

https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer/4
https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer/4/query?where=STATES%3D%27MN%27&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&having=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&historicMoment=&returnDistinctValues=false&resultOffset=&resultRecordCount=&queryByDistance=&returnExtentOnly=false&datumTransformation=&parameterValues=&rangeValues=&quantizationParameters=&featureEncoding=esriDefault&f=html
