### ISSUE TITLE
Thicken the HUC8 and change to orange

### ISSUE THREAD

**Issue by NathanKrawza** [USGS-WiM/MN-Low-Flow#76]
HUC8 Layer, the yellow color doesn’t contrast enough with many of the Basemap choices. 
HUC8 boundary lines were changed to thin line with alternating brown/white color.
The line is too thin and still doesn’t contrast enough with many of the Basemap choices. It shows up as a faint line not easily visible.
See the screenshot below with existing line and another screenshot with an example of better line color and thickness.

![download](https://user-images.githubusercontent.com/46204777/73028712-b7535980-3dfb-11ea-91d4-2bcfca6ba771.png)

Change the color to orange and thicken the line.

 -MPCA

**Comment by esmyers** [comment]
Bumped the thickness up to 1.5pt and changed to orange.  If this works, you can close the issue, otherwise, ping me and let me know if it needs additional tweaks.
